// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPaf22305yzbi23SZ6RxamtZJY6f26Yc',
    appId: '1:834423712130:web:1351b8114d9813e5f7479b',
    messagingSenderId: '834423712130',
    projectId: 'setting-up-flutter',
    authDomain: 'setting-up-flutter.firebaseapp.com',
    storageBucket: 'setting-up-flutter.appspot.com',
    measurementId: 'G-8TCHDG6JGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tW5wJPNlDymz4d9KFPDOMu3a2FexGns',
    appId: '1:834423712130:android:fc36c439711a7df3f7479b',
    messagingSenderId: '834423712130',
    projectId: 'setting-up-flutter',
    storageBucket: 'setting-up-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu_QSswAOHTP2NrKJSuCNpmvxQBtHyi2c',
    appId: '1:834423712130:ios:f3cd6f7b0a363c8bf7479b',
    messagingSenderId: '834423712130',
    projectId: 'setting-up-flutter',
    storageBucket: 'setting-up-flutter.appspot.com',
    iosBundleId: 'com.example.flutterInstagramLatest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu_QSswAOHTP2NrKJSuCNpmvxQBtHyi2c',
    appId: '1:834423712130:ios:f3cd6f7b0a363c8bf7479b',
    messagingSenderId: '834423712130',
    projectId: 'setting-up-flutter',
    storageBucket: 'setting-up-flutter.appspot.com',
    iosBundleId: 'com.example.flutterInstagramLatest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHPaf22305yzbi23SZ6RxamtZJY6f26Yc',
    appId: '1:834423712130:web:bcb3961ce9581edbf7479b',
    messagingSenderId: '834423712130',
    projectId: 'setting-up-flutter',
    authDomain: 'setting-up-flutter.firebaseapp.com',
    storageBucket: 'setting-up-flutter.appspot.com',
    measurementId: 'G-1Q2YQ74VN2',
  );
}
